title: guilleqp
description: Merlot is a theme for GitHub Pages.
theme: jekyll-theme-merlot

disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: my_disqus_shortname